package main

import "fmt"

func main() {
	partI()
	partII()
	partIII()
}

func partI() {
	input := "ABCCacCCbBAabcBbcBbaBBaBAAcAABCCBBACBbCCacacAbCcAAaAAacBAcbbbacAcAbcABAbaccAAAAABBaaccBbCCBABBCaBcca"
	countMentors := 0
	for i, char := range input {
		if char == 'a' {
			for j := range i {
				if input[j] == 'A' {
					countMentors++
				}
			}
		}
	}
	fmt.Println(countMentors)
}

func partII() {
	input := "ABCbBABbaCaacaBaabcaaAaBaaCCbbaCAbBaBaAAbbcababCAacbBaaCABACCCcccCccABCcaCAbBaaBcccCACbbccbAcCaabACBaacbAAbcbbacCabaBcBCbabccBbcbcBaccccBbBBacccaabccbaAAcBCbCCCCCccABBAAbcccACbAcbbCaccaCcacbaAaBbacABbCbcbCCaccBAbCaCbbaCbbAbcaaBBAAAACCaCBAAaabCaaaaaacbBaBBCCCBABcaBbBbbaCCaAACAACCcbAaaBccCcaaCCABbAcbc"
	countMentors := 0
	for i, char := range input {
		if char >= 'a' && char <= 'c' {
			for j := range i {
				if byte(char-32) == input[j] {
					countMentors++
				}
			}
		}
	}
	fmt.Println(countMentors)
}

func partIII() {
	/*
			Together with the captain, you agree that this assignment method is impractical. It will be far more effective to pair novices with mentors based on the distance between their tents. The final list contains all mentors and novices currently stationed in the garrison, and its order reflects the actual layout of the tents. However, you have noticed that this layout follows a repeating pattern, so you have recorded only the unique segment ( your notes ). This segment should be repeated  1000  times to represent the full arrangement of tents.
		You propose a method, which allows the novices to switch mentors without wasting time on relocation. To achieve this, the novice can only be mentored by knights who are on the list no further than  1000  tents to the left or right of the novice.
		Example based on the following notes:
		AABCBABCABCabcabcABCCBAACBCa
		For the sake of the example, we assume for now the distance limit between the mentor and the novice is only  10  instead of  1000 , and the pattern repeats  1  time instead of  1000  times.
		All of the mentors  M  who are close enough to each novice  N  have been marked below. For even better readability, the range limit of the current novice being verified is marked with  . .
		           N
		AABCBABCABCabcabcABCCBAACBCa
		 M...M..M........M....        = 4

		            N
		AABCBABCABCabcabcABCCBAACBCa
		  M.M.M..M........M..M.       = 6

		             N
		AABCBABCABCabcabcABCCBAACBCa
		   M...M..M........MM...      = 5

		              N
		AABCBABCABCabcabcABCCBAACBCa
		    .M..M........M....MM.     = 5

		               N
		AABCBABCABCabcabcABCCBAACBCa
		     .M..M........M..M...M    = 5

		                N
		AABCBABCABCabcabcABCCBAACBCa
		      .M..M........MM...M.M   = 6

		                           N
		AABCBABCABCabcabcABCCBAACBCa
		                 M....MM....  = 3
		To calculate the final result, simply add the number of possible mentors for each novice.
		4 + 6 + 5 + 5 + 5 + 6 + 3 =  34


		AABCBABCABCabcabcABCCBAACBCa
		For the same example, if we repeat the pattern  2  times, and still use the distance limit of  10 , we get following list of tents:
		AABCBABCABCabcabcABCCBAACBCaAABCBABCABCabcabcABCCBAACBCa
		with  72  novice-mentor pairs.


		AABCBABCABCabcabcABCCBAACBCa
		For the same example, if we repeat that pattern  1000  times, and use the distance limit of  1000 , we get  3442321  novice-mentor pairs.
		What is the total number of possible novice-mentor pairs?
	*/

	input := "AbbBaACbBbBbbcccBABcBbCCCaCABABacbcbABcCAcBBCBCbCbbBBaCBccCAbcCAbaCBAabBAbCcbCBABCbBcaaabaabCbbaAAAcaabBcAaaBbBcbAbaabBccbacbccCBAbaCBcacCbbBbBBcAAccaAbCCABAaAcAaacBCbBcBCbBbAbACABCaCabAcBACcbcBACcbbaCbCACaBBCAbCcBCBcAbBbaBcaCCaaAaCaBCbabBBABCAAbBBAAbccAcbBccbCACacbBCCBBCBcBaABbbabAbbbCbAACCCaCaCCACCcACCbbBbBAAACCcCBBbCCcAcbBBABCaBCbaCaCbbcCcaAcAaacCcaCBCAAcCbaBbACbaaBaCbbBcBBBAbbcACCcCcBaACaAABBCabACabAcaCCBbbcbCACACABabcCbabCcbAcabcaCabAaCbbCaabAAaACbbBAcaBAaccccaBaCBBCBCBCBaAccCaCAAabAbCaAaabaBBbbCCcACcBcAbCacabcBcAAbbCaABAAACBCbCcCBcaCCBbCbaCabcaBACcCccacbaBbBbaBbbcBbcABaCbaBbBBcAbBBabAaACaBabbBCabaBCbacbcBBaCACcCCbbcbBcbccbCCcABcCCaBACCbccABBCBabcacaCCABaCBAAcBcbBaBAbBCbcBcABBBccccccCBbaBbabbCBCaAAbAACcBbabCaAbACaaAACCBAcBAAbcacaBBbacCbacaCbCabAbabcbbacACBBBCAbabbbBbbbccCaaCcCaAcccACcAcAAaCBACbABacAcACcbBAbcCbBaBbBCBBbAACAACAcaAAcccAcBCCABcCCbCcbBBCBcacABaaCCbcBABCccCAAACbccCCaCccAaABAbaaAbbBaBAABCaBBCacACbaBCABAcBcbBBCAcbaCCCBcCAbccBcbcBBABBCCcCccCcaacAcCAACCBcbAAbAABBacCBCBBCAcCCAaCbcAbbCbBBbBACCbBaaBcaAbBbaCaaBABCCaAAcAACbBaCbACbBaBCCbBcCBACcCBCAcbcbBabcabAccCcBaBcbBBbbcBCbBcCBcbaaBaCCacbcaBbAbCbcBaaCAcbCbCcBcbACCCcAAbabaBaAbCbAaAaAacABcAaccbbcBbcABAACCbbCBaCAbccAAaABabccacCAbbccbCcABbABbaBBCCABCAabCBBaCCcBACCaBaAbBCCBcCBcbCaAAcBccAaCBbcBBAAACaaBABBAacBACcBaabccAABBbaCaccABBAaAaAAACBBCaAcAcCBCCCaaBaBBBbcCBaBcbABacbCbABcBBAcBBaaaabbCCabbCcbAbACBbBCCABacABBcACBbAcAAaAaCCACccAabccaCBBcAAaCCccccaBBbbCBAaCBCbbAAbaBacabCcCAcbACabccBcabACaCcbCAAcaCbbbAbcbcCCaaCAcccbCCBBaCBCabCcbbAaAAAaBCcccaaaCCabcABCaBcCcABaACACacBbbCCBABBabcCCaaCCBbCcabCBcacBabbCCAAaBAAbCBAAbACAbcaabBaaCbabbCbBcbBCABCAAcBAbbbCAaaACABAAbbBaacCbbAcbbBCbbcCaaABcBcAcCCacAaabcBaCbBaCABBcAabbbbbBCCBcCCBACcaCBACccCbaaccABBcBbaBCAcaCaCaAACAcbACBBCacBcbcaBBAccaaCbCCAcAACBaCCbCABcCAbAbBBcaCcCcaCaccAcAABaacBCaAaCbcbCCBBAaCaCabbabcaAacaAABaacAaaCaCaAAcCcCbBCcCbcaBaABCBabbbccaABcBbaccCbbCaCcBBAABCaCbbbbcbcCBABbABBBCaaBCbbcbAaaBaAACaBCBACaccABBBcAAaCcaBAbbbcCbbCbCCaccBaccacbcBbBBACbabCaAbBBbcacbccACAabCbbBaAAcbbbaAABbbBBbcccccbBAAAAaCAbbBAAbbCBCBabbabBAbcBCBcCbCbaAAcbBcAbBcccAcaBabCAcBCABCcbCaaACBBcABCBBBCbAccAAaaccAacCacaaaBccabcbBabCcaCBCACbabaBACCaaABCBaaCCBcBBbBCcaAcBACBaccacCabCacbcCbACbBcaCACaAcBCAbbbbbAaaABaBaBAbaACaBabCBcbbaaCBCCcacABcABCCbCcBccBabaAcccBACcaAcCAcAAbcABBbaCcCBACacaAAcCBbCaCbbbcCCBabCBbabBBaCcCAaaAbCCAACABbACABbABaABCCaACAcbcabAbBcbCBAcbbcbBCCCCaacCcAcCbbcbBBaAbACBbABBaBCAbbCBBBCAbcACCaabBcaaACBBBcBAbaCBABCcBcBBcCbaBAAaabcACBBbcABccbacAcAcCbAbacBBCaAabaCcCCcAacBcCaCaCBBbAaBbcaBaCaACaAbAcACbCBbBABbBcBbaaaACcabBCbbaCABbBaAbCcaaCCabbCaBacBcbaBABBBAaABaaCBBBBAaBaCbaAAcbbBCbcbCaACcBaacABAcCAAABabACAaABCCcCbbaAbbcCBBcaAbBcCcBbABAacacCBAbcCBbAcbbAcBaacaCaaacABbbABcAcCCbAACCaCbbabAaCCCbBbCbAcbbcBACccbAAbccBBCCaABCBBcabAbCCABAABaaaacbaCaCBBbCBCBbaCaaBbAAcBAbcabbBCABaCCCaaAAbAbBCcccacaBBAbcbaAbacCaBAbCCacCAABbbBaBBAaAAacbBCCabababbaBaAbbaBbcABcbCaCaccCAAACACBBcBBCBaAcAAAbbBBCAAcAcbACcabBcACBaCcBcBbACAbcBCAcAaBABCbbBAaAbbACBaCBACABbcbbaBCCbBcbBaBBCcccCBcABCaCBcBccbaCbaBCBCbaAACbcCabCAcbaBCCcCCbaCBABaCACBaBABaAccccBaCBBacCABBBCCAaccCaaCBaAaCBbbCBcaacccacCBbbbBBaAABbACbbCabaBacABbaCbaACabABBBACCCaABBCcbAcBAaCCbACcbBCcAaBBCCaAacbbcbCCcbbBbcAaacBabacbBCBAcAccabCcabCcabBCCCbBAaaCaabcabccBCCbACcCCbbbCbBCbbabBbBcAAaaaAABcabAAbbaBBacbBCbbaBAabCACCACBBbcbbBCaBACBccacBcCcabCcCBcbAbaacBABcCBBBCACbCBaACcAAbccaaaBbBCABcAbcaCbBaCACAaBCccbaabaccaCAacCaaAabBBCCCCACCaaaCAbbbcCBCaAAaAcaCBaCaAAbbbcCaAbAcCbAccBAcABcBbACBAaaaCaCabbbAbAbCcCCabAACbAbbCcaaccBbABabbaaabbBbbaCBcbbaBcbcbBbcCBCaaccCaAccbbBCBaAbaAabBBCbbbBBcccbbCbCACbbccAcBBAbcBaABaCaCAbabcbBBcbBACCAcAacBCBCaAcbccBAaABCaCbbccbccBbCaabBcaBaCAaACcAccCbAcAbbBcAABCAcaaCaAcAaCcAbaCababcbbCBacbcbBBCaCcCbBAbbaCCacabCBBaCBAbbCbBCbbcCcbBBccAaabCabCBBABBbCBbAaaCabbABAbBaabBBcabaCAbBabCAcaaccccccccAAAbCCCBaabccaCAAbCaccBBBaAcCBbbBaccAcABaBBaacAbbCCCabBcbCccBAbAbCACcaAbCAbaacBCBCCaABAbAcAAbAabBbbaBaccbbCAbCBabCaccBbbBcbCCbcAcABBcBaAaBCBaAbcCAaBACbCCCAbBaaBcABaBBbACCCbAcaBabCaCbaBBcCBcabCcAbAaABBcCaCAACcbBcAacbcaccAbBCbcBBacBBBCacbaAcBABaBcCaBcbBBbcCbaCaCaCABbCCBBbBAAABcabBCABcaBaCBbcAACAbCcCAbbcBBABCbAcbBbAAABcBABAACcBBacBaAcBaAbCAaccAAbAaABbCbbaBCCaACCACABbbCAaBACbABccCcCBccBaBcAabBCBACbAbCacaabcaaaCAbbbcBaaCCcBbbaBabbaBaabcbAbbacBAAcbbababaCACAACaAbcbCbcCAAbcAbBacAbCaccbCAcbaBAAcaCbACcBACbbbcCcbABCBCbCAcbAccABBBbCACbbbbccBBaAAaACbcCCaABbBBCbaBacbaBAcCccbBbCcCccbBaaaaACcCAcaCBAcaaBAbBaBCaCCAbcBbacCBAaBBbABabCBAaACcBcaBbABABAcaBBacCBaCBAacAccAAcbBcAABBcbBABcAaccBCbABcccAacbBCCcaAaCBcaBaBCAcbCBCAabcCCBbBAbcbAaAbbcABAaCbBBaAAccCaaAccAcaaCaBbBbbcaCbACCAaBaaBbbbAacaCCBcbcACCaccAccbbacCCBAbbbabBBCbACBAacaAAcbBCBcCcBCcaABbABCBcABCACbBbacbAbacbABbaCaaAABabBAAAAcaCBCBCAbcAaBCaCBCbCbAccaCbaacBabcBbccBAcCABcBaccbbAAccBCAcCbCAcBCBacAAbacaBCCCcbBaaacABbbBbBCAABBbCcAAabcBBAAaCAbCABaabcBacCAAcbBBAccAbbbbcBCcababaaACABBBbBbcBAaAAcccACaBCAbACAaABCBCAaaaAabbCACCBcCCcBccABAaaAbbccbabAaaACbbBABcaCaAaaCbBCCcAbBbbacbAAAacAaccBAbCbCaBCbacbCAbCbBcBABCABBabbcCccCbcbbbcabBBBcAaCAacACBcBcAbaCAAacAaaAcaAaBCaCcACBaaCAcCBABbcbccCAaACcaacBBACcBbABbcbBBcBaBBcABCbABaBacACcBAcCABAcaBaCaAAcBbACcABCcbAaccBacccaCcCaACaCCaBaCcCaACBCBCAabbaBBcCcBAABcacbCaCCcCbcabcaaABacbCcACBabcacCABacCaCaBbcCcbcBaaccacBABAbACbbcBCbAABBaBAbacAcabBACBccAcABBbBCCaCccaCBacAAcAbCcbccAccacacBBbcAcccaAABAAccaccBbBbCABbCbaCaBbacAbabBCbbabAAbCaBBCbcBABBcCCCcCBCbCCBcAbCbABaAbcCCcbBCbBabABBbbbAbAabacbbcbaccBbABAbBBBacCCcAbcAcacBAACbAACabbaabAaCcbaCaACAbacAaBBCaBacBBabcCAaaCBBacAACcbAbbbCbbbCbaaaACbcabBaBABAAAACccBAbaABCbaCbbbbbcCCBBcBcBaCaCaBbABCbbCBbCAbBbbCcCBCbAacbcacAccBBbbcCBcbccAbbACBBAcCbbBacccBCaBBaabaAabCaCABAACaCAAABbcBaCbCaCbACBbBcCCcbaCBCbbcccAcABAAcBabaccCBabCcAAAAaBcCbcACCCBbBaBacAcAAACaCAbCaaBbaabbCBacbbBccccCBcCbbCaCbCACCBAAcbabCBaAcAcBBAABAaBbBBbBBBCcCccaCAcaBCcAaccaCAcAAaBCABCcacacCbCbbCCBcacbbaAcBBcCbCBbACBbCbaaCCBaCabAbAaCaAacBaAAcBCBCaaaCABBbaCCACaBCBCcCcBACAcBACCbcCBbcaBaABbaAcCbBaBcCCCCAbBabaCcAbBAaBCBabCcacBCbBCCacBAAaCabAbcBbCAACBCAAbabAcCbAcBaAABAbCCBccaAAaBaccCcCacBabacCCaBCCaaaAabaabCBbbcABcaCBbcBcBbBbBcbcBaAbccAABCBcaCACAcACAaBBCcBcBbAccaBcCbbcacAacbBcBAcBcacbABCAbABaccCcCAbccAacAAcAcCCBCbcbBCAAACCbabCcAAbabCacccbccbcbaBBBcbaBbBAabaabcAabBaCaaaCaCaCBaBaAAcACbbCAAbABBCBabaACABAbBAAacBcBCBbcACAacCCCccABCBbcaABbCbcBAacCccaaBabbAACaccaAbCCCaaBCBCaCacaaCcCabbAbacaBbCBAbBBBcBAbCacBCaAAAbBBBCcCACAcCaAbAcAAACbbbCbaabaacACaBBBBABabaAcaAAbACAbbcbBCBccaACbAaCaBaCAbACbBaaAAAaaBBBaAAaCAAbcBaaaaBabbAcbCabBaBcaBABaabAAACaAcCbCBBBaCcBaBCbAbCCcAbAaBbBcBCcAAbaaCCcBAabBbaBbacBCACABAbbBcCcbBbcaBcBBcCCaCBBCCbBcacCAcBbcCBbBAcaaAAabAAcBcabCAbcBbAccbcccccBbCaccCCBccaccaabBBBACcccBaABABBcbAbcAbCaBBCBAcaabbaABbaacBBBcACBCbaAacbAABCbcABcCCAbbaAbcaCcCbCacaacbbCccAcBBbbBAcAAabaBaABbCcCaCaaCaBcCbBBcaAaAcCaAaAaCcCaCAbaBAbaccbcbBaBCbcCCCACCcaacABCCcaACCBabCbBaBccAcACAAAbCcACacCACBaBACccbabaaCbbbBBcBbcbCBBCabCACCcacbcbBbcCACbBAAaCcBAAaCCAaBBcaBcCcBcBcBCBBbCbBccCBCaAABccccaBcbAAACbcBbbBbbacBBAacBCaaBaCbBCcBbacaACaaABaCaBaBBbAcBABAaBBAACBcaBcaAacbABBCbCaBcABbACCacCcCcABABACaCbcACcbaCaababcaacAABbBAaccabBAaABacabCBCaaCCbAabABCaBcbCbBcBaABABbabaaBabCACBABabbcbaCCabAABbCaBaACCBBcAcBBbBCAaaaaCBABcABBCcCAcBCBBbBccCbAaCBCaacBccCacAcACCccAbACABCBbbBCBbcbBcaBBacBbaaBCaAaCBcACbAbCAABCCacCBbBAcbaacCCcAABAAbBaAcbAcaaaaabCcbBaabBAbabAaabAcaCcAABACcBbcaaBaAcbBBbbccCBAAbACAbBbCBCbccCcCBccCBABcCabbACcbAbBBAaBBcCCcabAccaCAAcbBBccaacaaBABbCaBCabCBbaAABAcBcbccccBAcCcCacAAbccBABcCAcCaCBbcACCaAcbcCBACACbCcbaCbCcccacCaacabCcAaCAACaACaACaAAbbAacCcAaBaACBbAaBACBBccaABbACCCAbCBCCccccAcbcBCCBAaccAbbAabBccbCbCaCaaAaBCaaaBcbCBCBaaBbCbaBbCCABaAaabAAAAabbbAbacBcCCcaAAcaccCCbccAcaCBcccbCcAcABbAcbBbBcCBAccaaccaCCBBaacbACBCCCCbAaACBcAccBcBccbbbBCBaacBbACbbbaBACBCCbcabAcabCBCaBaABACcbCAcccBaBcBACbAAAacCcCBBbAAABabCACaccbBAAbbcAbaacCAbBaCcCcCCcAAaAABaaAbCBaCBBABBbACbacAbCbaaAccAaCcAaACcCBcbbcbccACAcBcCACbACACbCcCcbBCBbabbAbBABbBABcACACCcaaABcaABBABBbABaACcCCBacaBaBCBaCBBaCbCCaAaCaaCBBCACbcBCCBbBccCbBCbCaccaaBBcBCBCABCbBAcBbaaCCCcAabBbcCCbCCBbAABcBCCbbBbBcBcBBbaBaaCAbBbCbAAAaBbbaCbBAbAbCCAaccACCcbcAcaABAaAABaCBaaCccBbCAbcbAbACaAcBacBAbBCCacCACbcBBbaCAabccBcBbCcbaCcbAbacBBbACbbBccBBBAaCBcbCAcCbBCaCacAcbacbcCAbbcccBCbCABacBAcaBbBbbcAccABbACAAabBcAaACBcBcaBAAbBaBBabCbCaBAaCaBaaaAcbAcBbBcAbabcaBccABcBCAAacBaAaAcBCCAaBBABBcBBcCCaBacAbbCBBcCBCbBbAABBcbAbBcCABBBbACBCAabaAABbAAaBCCCbaBcacacbaccCBaAACbCAACaCAaaBABAaBcCBbbcbaccbaCBaBBabBabcCbbBbCbaCBbCCCbbcABBbBaBbcBCaacCaCbcabAAbbbBCAAaABAAbbCAAcACAAAcaacBbcBCaAabBcbaaCcCAAaCBAbcBcabcaBcAcbBCBABBAbaAbBCaABcABacAabcaccBCBacABCCcCcBbaccbBcAcCbabAcBacAbbAAbabbaAabaAaBBCAcbcbcAABaBcBbabcCcacccbCacBaACacbcccccCaaCBabCBBCBbBCcbBAaBAaCCabACbcaCaCCAaCCcbCCCCABBCbCacabBAbaAcbBBcaCCCBabCbcBCcBbaACcbCbcBBBABACcBCBBcbCBBacbbAbAAbbBbcBaaaAABbcACbacAbCCbabcbaBCcbbbcCbAcABBabBCbBCBccBBCABAAAbAAacBCcBAbCBBaaACacaBccaacbBacaBAabcbBaCabaBBBaACCbccaBCABAbcAbACBAabacaBBABcCCBbAabBbAABBbBAbCBBAcaBaabaBcacBbaCAbacCABABbAaaAcaCACCBcAABCBBcBBbBBBbABBBAaaaCaaCBabCBbCcbaaAcbCaaBCcBBbbaCcAAaaaABACCbaAbbCabbabbcabCcCccACCAccaBbBCCbcbcacBBcACBbBCbBCAabcBaBCbBcBbBAAccbbbCaCAAaabaaBCaCCaBcBBCBaBAaAaAAaCaBCaAaBcbccAbcccAbbaCcAAABAacaCAAcABABcCabcbaBacbBBaBcbcBBCcaaACacAacBBBCaBCAbBAbbAaaaACBaabaBaACcAbcBABaaAAAbbbbcCcBcBAAbcbAbcCbcBCBAbAbbabBBaCcAABABcAcBAbAcbAaBaBAcAbAabAAaCccCAcAbcbBAcbbcbbbAaaaCBCbcbAABCAaAbcBacabaBCBBBACbbBbcaCaBBCBBbAccAacaAbABCabCcbcBCbcaBBCcAcaAAaBaBbbbabcBbaacbccbBCcAAabCAabbcCBaBCcAbbaAaBAbabACAabaabBbbacCABAcbbABBACcCCACCbCbBcbaacAbacBAbbACcaCAcAAcaACAcAbcaBbBbbcbAaaBcAAacAbCbcbAcBCcbbcCbAcCBaAbabcACbBabccAbBccaBAbaAcaaaabCbCcCBBcbAbaCbBCbAacCCCaCbaaCabaAbabAaBCaBbAAcbccAcabCCCbaaBCabcbCcaAAAaBBBaAbBbabBaBbcCcAbABbCBbAaacaBabcCAbBabcbCaCabaBbACaBabCbBabbACBBCcbaaACCAbbCcCbCccAbAacaAAbbcacaBCACaBaACBaCbbBBcaABcCABBaacBbccBbcbCBcCaBCcCAaBCCacAbbAaaaBAAcaAccCcbcbacBaabcCBacacbaACBABBcaBbCAAaBacbBbAcBABBaABBCACcAcABCAAcbbcCABCCaBbAcAaaabaaCBBCAbCcaaAAAAbaCBaaABaaABcAcBbcAAcccAbBcbCBccabcCCBBBcCbabAACaABaaBBaabcaACcbcAaaBaabaAABaAcbbAAbcCAcBABAbAbcBbbccabCaBBCaAAacaacaCcBcaACABcaBABCbBcABABaABabBAaCcCAacaCAcCaACcBAaACbbcBCBcAcCabcAcAcbcbCcabbBaBbcCacBaCcAbacCAACAacAabbBAACBBacbCBcCaAbcAaa"

	patternLength := len(input)
	repetitions := 1000
	totalLength := patternLength * repetitions

	countMentors := 0
	for i := range totalLength {
		char := input[i%patternLength]
		if char >= 'a' && char <= 'c' {
			for j := i - 1000; j < i; j++ {
				if j >= 0 {
					mentorChar := input[j%patternLength]
					if byte(char-32) == mentorChar {
						countMentors++
					}
				}
			}
			for j := i + 1; j <= i+1000; j++ {
				if j < totalLength {
					mentorChar := input[j%patternLength]
					if byte(char-32) == mentorChar {
						countMentors++
					}
				}
			}
		}
	}
	fmt.Println(countMentors)
}
