package main

import "fmt"

func main() {
	partI()
	partII()
	partIII()
}

func partI() {
	input := "ABCCacCCbBAabcBbcBbaBBaBAAcAABCCBBACBbCCacacAbCcAAaAAacBAcbbbacAcAbcABAbaccAAAAABBaaccBbCCBABBCaBcca"
	countMentors := 0
	for i, char := range input {
		if char == 'a' {
			for j := range i {
				if input[j] == 'A' {
					countMentors++
				}
			}
		}
	}
	fmt.Println(countMentors)
}

func partII() {
	input := "ABCbBABbaCaacaBaabcaaAaBaaCCbbaCAbBaBaAAbbcababCAacbBaaCABACCCcccCccABCcaCAbBaaBcccCACbbccbAcCaabACBaacbAAbcbbacCabaBcBCbabccBbcbcBaccccBbBBacccaabccbaAAcBCbCCCCCccABBAAbcccACbAcbbCaccaCcacbaAaBbacABbCbcbCCaccBAbCaCbbaCbbAbcaaBBAAAACCaCBAAaabCaaaaaacbBaBBCCCBABcaBbBbbaCCaAACAACCcbAaaBccCcaaCCABbAcbc"
	countMentors := 0
	for i, char := range input {
		if char >= 'a' && char <= 'c' {
			for j := range i {
				if byte(char-32) == input[j] {
					countMentors++
				}
			}
		}
	}
	fmt.Println(countMentors)
}

func partIII() {
	input := "AbbBaACbBbBbbcccBABcBbCCCaCABABacbcbABcCAcBBCBCbCbbBBaCBccCAbcCAbaCBAabBAbCcbCBABCbBcaaabaabCbbaAAAcaabBcAaaBbBcbAbaabBccbacbccCBAbaCBcacCbbBbBBcAAccaAbCCABAaAcAaacBCbBcBCbBbAbACABCaCabAcBACcbcBACcbbaCbCACaBBCAbCcBCBcAbBbaBcaCCaaAaCaBCbabBBABCAAbBBAAbccAcbBccbCACacbBCCBBCBcBaABbbabAbbbCbAACCCaCaCCACCcACCbbBbBAAACCcCBBbCCcAcbBBABCaBCbaCaCbbcCcaAcAaacCcaCBCAAcCbaBbACbaaBaCbbBcBBBAbbcACCcCcBaACaAABBCabACabAcaCCBbbcbCACACABabcCbabCcbAcabcaCabAaCbbCaabAAaACbbBAcaBAaccccaBaCBBCBCBCBaAccCaCAAabAbCaAaabaBBbbCCcACcBcAbCacabcBcAAbbCaABAAACBCbCcCBcaCCBbCbaCabcaBACcCccacbaBbBbaBbbcBbcABaCbaBbBBcAbBBabAaACaBabbBCabaBCbacbcBBaCACcCCbbcbBcbccbCCcABcCCaBACCbccABBCBabcacaCCABaCBAAcBcbBaBAbBCbcBcABBBccccccCBbaBbabbCBCaAAbAACcBbabCaAbACaaAACCBAcBAAbcacaBBbacCbacaCbCabAbabcbbacACBBBCAbabbbBbbbccCaaCcCaAcccACcAcAAaCBACbABacAcACcbBAbcCbBaBbBCBBbAACAACAcaAAcccAcBCCABcCCbCcbBBCBcacABaaCCbcBABCccCAAACbccCCaCccAaABAbaaAbbBaBAABCaBBCacACbaBCABAcBcbBBCAcbaCCCBcCAbccBcbcBBABBCCcCccCcaacAcCAACCBcbAAbAABBacCBCBBCAcCCAaCbcAbbCbBBbBACCbBaaBcaAbBbaCaaBABCCaAAcAACbBaCbACbBaBCCbBcCBACcCBCAcbcbBabcabAccCcBaBcbBBbbcBCbBcCBcbaaBaCCacbcaBbAbCbcBaaCAcbCbCcBcbACCCcAAbabaBaAbCbAaAaAacABcAaccbbcBbcABAACCbbCBaCAbccAAaABabccacCAbbccbCcABbABbaBBCCABCAabCBBaCCcBACCaBaAbBCCBcCBcbCaAAcBccAaCBbcBBAAACaaBABBAacBACcBaabccAABBbaCaccABBAaAaAAACBBCaAcAcCBCCCaaBaBBBbcCBaBcbABacbCbABcBBAcBBaaaabbCCabbCcbAbACBbBCCABacABBcACBbAcAAaAaCCACccAabccaCBBcAAaCCccccaBBbbCBAaCBCbbAAbaBacabCcCAcbACabccBcabACaCcbCAAcaCbbbAbcbcCCaaCAcccbCCBBaCBCabCcbbAaAAAaBCcccaaaCCabcABCaBcCcABaACACacBbbCCBABBabcCCaaCCBbCcabCBcacBabbCCAAaBAAbCBAAbACAbcaabBaaCbabbCbBcbBCABCAAcBAbbbCAaaACABAAbbBaacCbbAcbbBCbbcCaaABcBcAcCCacAaabcBaCbBaCABBcAabbbbbBCCBcCCBACcaCBACccCbaaccABBcBbaBCAcaCaCaAACAcbACBBCacBcbcaBBAccaaCbCCAcAACBaCCbCABcCAbAbBBcaCcCcaCaccAcAABaacBCaAaCbcbCCBBAaCaCabbabcaAacaAABaacAaaCaCaAAcCcCbBCcCbcaBaABCBabbbccaABcBbaccCbbCaCcBBAABCaCbbbbcbcCBABbABBBCaaBCbbcbAaaBaAACaBCBACaccABBBcAAaCcaBAbbbcCbbCbCCaccBaccacbcBbBBACbabCaAbBBbcacbccACAabCbbBaAAcbbbaAABbbBBbcccccbBAAAAaCAbbBAAbbCBCBabbabBAbcBCBcCbCbaAAcbBcAbBcccAcaBabCAcBCABCcbCaaACBBcABCBBBCbAccAAaaccAacCacaaaBccabcbBabCcaCBCACbabaBACCaaABCBaaCCBcBBbBCcaAcBACBaccacCabCacbcCbACbBcaCACaAcBCAbbbbbAaaABaBaBAbaACaBabCBcbbaaCBCCcacABcABCCbCcBccBabaAcccBACcaAcCAcAAbcABBbaCcCBACacaAAcCBbCaCbbbcCCBabCBbabBBaCcCAaaAbCCAACABbACABbABaABCCaACAcbcabAbBcbCBAcbbcbBCCCCaacCcAcCbbcbBBaAbACBbABBaBCAbbCBBBCAbcACCaabBcaaACBBBcBAbaCBABCcBcBBcCbaBAAaabcACBBbcABccbacAcAcCbAbacBBCaAabaCcCCcAacBcCaCaCBBbAaBbcaBaCaACaAbAcACbCBbBABbBcBbaaaACcabBCbbaCABbBaAbCcaaCCabbCaBacBcbaBABBBAaABaaCBBBBAaBaCbaAAcbbBCbcbCaACcBaacABAcCAAABabACAaABCCcCbbaAbbcCBBcaAbBcCcBbABAacacCBAbcCBbAcbbAcBaacaCaaacABbbABcAcCCbAACCaCbbabAaCCCbBbCbAcbbcBACccbAAbccBBCCaABCBBcabAbCCABAABaaaacbaCaCBBbCBCBbaCaaBbAAcBAbcabbBCABaCCCaaAAbAbBCcccacaBBAbcbaAbacCaBAbCCacCAABbbBaBBAaAAacbBCCabababbaBaAbbaBbcABcbCaCaccCAAACACBBcBBCBaAcAAAbbBBCAAcAcbACcabBcACBaCcBcBbACAbcBCAcAaBABCbbBAaAbbACBaCBACABbcbbaBCCbBcbBaBBCcccCBcABCaCBcBccbaCbaBCBCbaAACbcCabCAcbaBCCcCCbaCBABaCACBaBABaAccccBaCBBacCABBBCCAaccCaaCBaAaCBbbCBcaacccacCBbbbBBaAABbACbbCabaBacABbaCbaACabABBBACCCaABBCcbAcBAaCCbACcbBCcAaBBCCaAacbbcbCCcbbBbcAaacBabacbBCBAcAccabCcabCcabBCCCbBAaaCaabcabccBCCbACcCCbbbCbBCbbabBbBcAAaaaAABcabAAbbaBBacbBCbbaBAabCACCACBBbcbbBCaBACBccacBcCcabCcCBcbAbaacBABcCBBBCACbCBaACcAAbccaaaBbBCABcAbcaCbBaCACAaBCccbaabaccaCAacCaaAabBBCCCCACCaaaCAbbbcCBCaAAaAcaCBaCaAAbbbcCaAbAcCbAccBAcABcBbACBAaaaCaCabbbAbAbCcCCabAACbAbbCcaaccBbABabbaaabbBbbaCBcbbaBcbcbBbcCBCaaccCaAccbbBCBaAbaAabBBCbbbBBcccbbCbCACbbccAcBBAbcBaABaCaCAbabcbBBcbBACCAcAacBCBCaAcbccBAaABCaCbbccbccBbCaabBcaBaCAaACcAccCbAcAbbBcAABCAcaaCaAcAaCcAbaCababcbbCBacbcbBBCaCcCbBAbbaCCacabCBBaCBAbbCbBCbbcCcbBBccAaabCabCBBABBbCBbAaaCabbABAbBaabBBcabaCAbBabCAcaaccccccccAAAbCCCBaabccaCAAbCaccBBBaAcCBbbBaccAcABaBBaacAbbCCCabBcbCccBAbAbCACcaAbCAbaacBCBCCaABAbAcAAbAabBbbaBaccbbCAbCBabCaccBbbBcbCCbcAcABBcBaAaBCBaAbcCAaBACbCCCAbBaaBcABaBBbACCCbAcaBabCaCbaBBcCBcabCcAbAaABBcCaCAACcbBcAacbcaccAbBCbcBBacBBBCacbaAcBABaBcCaBcbBBbcCbaCaCaCABbCCBBbBAAABcabBCABcaBaCBbcAACAbCcCAbbcBBABCbAcbBbAAABcBABAACcBBacBaAcBaAbCAaccAAbAaABbCbbaBCCaACCACABbbCAaBACbABccCcCBccBaBcAabBCBACbAbCacaabcaaaCAbbbcBaaCCcBbbaBabbaBaabcbAbbacBAAcbbababaCACAACaAbcbCbcCAAbcAbBacAbCaccbCAcbaBAAcaCbACcBACbbbcCcbABCBCbCAcbAccABBBbCACbbbbccBBaAAaACbcCCaABbBBCbaBacbaBAcCccbBbCcCccbBaaaaACcCAcaCBAcaaBAbBaBCaCCAbcBbacCBAaBBbABabCBAaACcBcaBbABABAcaBBacCBaCBAacAccAAcbBcAABBcbBABcAaccBCbABcccAacbBCCcaAaCBcaBaBCAcbCBCAabcCCBbBAbcbAaAbbcABAaCbBBaAAccCaaAccAcaaCaBbBbbcaCbACCAaBaaBbbbAacaCCBcbcACCaccAccbbacCCBAbbbabBBCbACBAacaAAcbBCBcCcBCcaABbABCBcABCACbBbacbAbacbABbaCaaAABabBAAAAcaCBCBCAbcAaBCaCBCbCbAccaCbaacBabcBbccBAcCABcBaccbbAAccBCAcCbCAcBCBacAAbacaBCCCcbBaaacABbbBbBCAABBbCcAAabcBBAAaCAbCABaabcBacCAAcbBBAccAbbbbcBCcababaaACABBBbBbcBAaAAcccACaBCAbACAaABCBCAaaaAabbCACCBcCCcBccABAaaAbbccbabAaaACbbBABcaCaAaaCbBCCcAbBbbacbAAAacAaccBAbCbCaBCbacbCAbCbBcBABCABBabbcCccCbcbbbcabBBBcAaCAacACBcBcAbaCAAacAaaAcaAaBCaCcACBaaCAcCBABbcbccCAaACcaacBBACcBbABbcbBBcBaBBcABCbABaBacACcBAcCABAcaBaCaAAcBbACcABCcbAaccBacccaCcCaACaCCaBaCcCaACBCBCAabbaBBcCcBAABcacbCaCCcCbcabcaaABacbCcACBabcacCABacCaCaBbcCcbcBaaccacBABAbACbbcBCbAABBaBAbacAcabBACBccAcABBbBCCaCccaCBacAAcAbCcbccAccacacBBbcAcccaAABAAccaccBbBbCABbCbaCaBbacAbabBCbbabAAbCaBBCbcBABBcCCCcCBCbCCBcAbCbABaAbcCCcbBCbBabABBbbbAbAabacbbcbaccBbABAbBBBacCCcAbcAcacBAACbAACabbaabAaCcbaCaACAbacAaBBCaBacBBabcCAaaCBBacAACcbAbbbCbbbCbaaaACbcabBaBABAAAACccBAbaABCbaCbbbbbcCCBBcBcBaCaCaBbABCbbCBbCAbBbbCcCBCbAacbcacAccBBbbcCBcbccAbbACBBAcCbbBacccBCaBBaabaAabCaCABAACaCAAABbcBaCbCaCbACBbBcCCcbaCBCbbcccAcABAAcBabaccCBabCcAAAAaBcCbcACCCBbBaBacAcAAACaCAbCaaBbaabbCBacbbBccccCBcCbbCaCbCACCBAAcbabCBaAcAcBBAABAaBbBBbBBBCcCccaCAcaBCcAaccaCAcAAaBCABCcacacCbCbbCCBcacbbaAcBBcCbCBbACBbCbaaCCBaCabAbAaCaAacBaAAcBCBCaaaCABBbaCCACaBCBCcCcBACAcBACCbcCBbcaBaABbaAcCbBaBcCCCCAbBabaCcAbBAaBCBabCcacBCbBCCacBAAaCabAbcBbCAACBCAAbabAcCbAcBaAABAbCCBccaAAaBaccCcCacBabacCCaBCCaaaAabaabCBbbcABcaCBbcBcBbBbBcbcBaAbccAABCBcaCACAcACAaBBCcBcBbAccaBcCbbcacAacbBcBAcBcacbABCAbABaccCcCAbccAacAAcAcCCBCbcbBCAAACCbabCcAAbabCacccbccbcbaBBBcbaBbBAabaabcAabBaCaaaCaCaCBaBaAAcACbbCAAbABBCBabaACABAbBAAacBcBCBbcACAacCCCccABCBbcaABbCbcBAacCccaaBabbAACaccaAbCCCaaBCBCaCacaaCcCabbAbacaBbCBAbBBBcBAbCacBCaAAAbBBBCcCACAcCaAbAcAAACbbbCbaabaacACaBBBBABabaAcaAAbACAbbcbBCBccaACbAaCaBaCAbACbBaaAAAaaBBBaAAaCAAbcBaaaaBabbAcbCabBaBcaBABaabAAACaAcCbCBBBaCcBaBCbAbCCcAbAaBbBcBCcAAbaaCCcBAabBbaBbacBCACABAbbBcCcbBbcaBcBBcCCaCBBCCbBcacCAcBbcCBbBAcaaAAabAAcBcabCAbcBbAccbcccccBbCaccCCBccaccaabBBBACcccBaABABBcbAbcAbCaBBCBAcaabbaABbaacBBBcACBCbaAacbAABCbcABcCCAbbaAbcaCcCbCacaacbbCccAcBBbbBAcAAabaBaABbCcCaCaaCaBcCbBBcaAaAcCaAaAaCcCaCAbaBAbaccbcbBaBCbcCCCACCcaacABCCcaACCBabCbBaBccAcACAAAbCcACacCACBaBACccbabaaCbbbBBcBbcbCBBCabCACCcacbcbBbcCACbBAAaCcBAAaCCAaBBcaBcCcBcBcBCBBbCbBccCBCaAABccccaBcbAAACbcBbbBbbacBBAacBCaaBaCbBCcBbacaACaaABaCaBaBBbAcBABAaBBAACBcaBcaAacbABBCbCaBcABbACCacCcCcABABACaCbcACcbaCaababcaacAABbBAaccabBAaABacabCBCaaCCbAabABCaBcbCbBcBaABABbabaaBabCACBABabbcbaCCabAABbCaBaACCBBcAcBBbBCAaaaaCBABcABBCcCAcBCBBbBccCbAaCBCaacBccCacAcACCccAbACABCBbbBCBbcbBcaBBacBbaaBCaAaCBcACbAbCAABCCacCBbBAcbaacCCcAABAAbBaAcbAcaaaaabCcbBaabBAbabAaabAcaCcAABACcBbcaaBaAcbBBbbccCBAAbACAbBbCBCbccCcCBccCBABcCabbACcbAbBBAaBBcCCcabAccaCAAcbBBccaacaaBABbCaBCabCBbaAABAcBcbccccBAcCcCacAAbccBABcCAcCaCBbcACCaAcbcCBACACbCcbaCbCcccacCaacabCcAaCAACaACaACaAAbbAacCcAaBaACBbAaBACBBccaABbACCCAbCBCCccccAcbcBCCBAaccAbbAabBccbCbCaCaaAaBCaaaBcbCBCBaaBbCbaBbCCABaAaabAAAAabbbAbacBcCCcaAAcaccCCbccAcaCBcccbCcAcABbAcbBbBcCBAccaaccaCCBBaacbACBCCCCbAaACBcAccBcBccbbbBCBaacBbACbbbaBACBCCbcabAcabCBCaBaABACcbCAcccBaBcBACbAAAacCcCBBbAAABabCACaccbBAAbbcAbaacCAbBaCcCcCCcAAaAABaaAbCBaCBBABBbACbacAbCbaaAccAaCcAaACcCBcbbcbccACAcBcCACbACACbCcCcbBCBbabbAbBABbBABcACACCcaaABcaABBABBbABaACcCCBacaBaBCBaCBBaCbCCaAaCaaCBBCACbcBCCBbBccCbBCbCaccaaBBcBCBCABCbBAcBbaaCCCcAabBbcCCbCCBbAABcBCCbbBbBcBcBBbaBaaCAbBbCbAAAaBbbaCbBAbAbCCAaccACCcbcAcaABAaAABaCBaaCccBbCAbcbAbACaAcBacBAbBCCacCACbcBBbaCAabccBcBbCcbaCcbAbacBBbACbbBccBBBAaCBcbCAcCbBCaCacAcbacbcCAbbcccBCbCABacBAcaBbBbbcAccABbACAAabBcAaACBcBcaBAAbBaBBabCbCaBAaCaBaaaAcbAcBbBcAbabcaBccABcBCAAacBaAaAcBCCAaBBABBcBBcCCaBacAbbCBBcCBCbBbAABBcbAbBcCABBBbACBCAabaAABbAAaBCCCbaBcacacbaccCBaAACbCAACaCAaaBABAaBcCBbbcbaccbaCBaBBabBabcCbbBbCbaCBbCCCbbcABBbBaBbcBCaacCaCbcabAAbbbBCAAaABAAbbCAAcACAAAcaacBbcBCaAabBcbaaCcCAAaCBAbcBcabcaBcAcbBCBABBAbaAbBCaABcABacAabcaccBCBacABCCcCcBbaccbBcAcCbabAcBacAbbAAbabbaAabaAaBBCAcbcbcAABaBcBbabcCcacccbCacBaACacbcccccCaaCBabCBBCBbBCcbBAaBAaCCabACbcaCaCCAaCCcbCCCCABBCbCacabBAbaAcbBBcaCCCBabCbcBCcBbaACcbCbcBBBABACcBCBBcbCBBacbbAbAAbbBbcBaaaAABbcACbacAbCCbabcbaBCcbbbcCbAcABBabBCbBCBccBBCABAAAbAAacBCcBAbCBBaaACacaBccaacbBacaBAabcbBaCabaBBBaACCbccaBCABAbcAbACBAabacaBBABcCCBbAabBbAABBbBAbCBBAcaBaabaBcacBbaCAbacCABABbAaaAcaCACCBcAABCBBcBBbBBBbABBBAaaaCaaCBabCBbCcbaaAcbCaaBCcBBbbaCcAAaaaABACCbaAbbCabbabbcabCcCccACCAccaBbBCCbcbcacBBcACBbBCbBCAabcBaBCbBcBbBAAccbbbCaCAAaabaaBCaCCaBcBBCBaBAaAaAAaCaBCaAaBcbccAbcccAbbaCcAAABAacaCAAcABABcCabcbaBacbBBaBcbcBBCcaaACacAacBBBCaBCAbBAbbAaaaACBaabaBaACcAbcBABaaAAAbbbbcCcBcBAAbcbAbcCbcBCBAbAbbabBBaCcAABABcAcBAbAcbAaBaBAcAbAabAAaCccCAcAbcbBAcbbcbbbAaaaCBCbcbAABCAaAbcBacabaBCBBBACbbBbcaCaBBCBBbAccAacaAbABCabCcbcBCbcaBBCcAcaAAaBaBbbbabcBbaacbccbBCcAAabCAabbcCBaBCcAbbaAaBAbabACAabaabBbbacCABAcbbABBACcCCACCbCbBcbaacAbacBAbbACcaCAcAAcaACAcAbcaBbBbbcbAaaBcAAacAbCbcbAcBCcbbcCbAcCBaAbabcACbBabccAbBccaBAbaAcaaaabCbCcCBBcbAbaCbBCbAacCCCaCbaaCabaAbabAaBCaBbAAcbccAcabCCCbaaBCabcbCcaAAAaBBBaAbBbabBaBbcCcAbABbCBbAaacaBabcCAbBabcbCaCabaBbACaBabCbBabbACBBCcbaaACCAbbCcCbCccAbAacaAAbbcacaBCACaBaACBaCbbBBcaABcCABBaacBbccBbcbCBcCaBCcCAaBCCacAbbAaaaBAAcaAccCcbcbacBaabcCBacacbaACBABBcaBbCAAaBacbBbAcBABBaABBCACcAcABCAAcbbcCABCCaBbAcAaaabaaCBBCAbCcaaAAAAbaCBaaABaaABcAcBbcAAcccAbBcbCBccabcCCBBBcCbabAACaABaaBBaabcaACcbcAaaBaabaAABaAcbbAAbcCAcBABAbAbcBbbccabCaBBCaAAacaacaCcBcaACABcaBABCbBcABABaABabBAaCcCAacaCAcCaACcBAaACbbcBCBcAcCabcAcAcbcbCcabbBaBbcCacBaCcAbacCAACAacAabbBAACBBacbCBcCaAbcAaa"

	patternLength := len(input)
	repetitions := 1000
	totalLength := patternLength * repetitions

	countMentors := 0
	for i := range totalLength {
		char := input[i%patternLength]
		if char >= 'a' && char <= 'c' {
			for j := i - 1000; j < i; j++ {
				if j >= 0 {
					mentorChar := input[j%patternLength]
					if byte(char-32) == mentorChar {
						countMentors++
					}
				}
			}
			for j := i + 1; j <= i+1000; j++ {
				if j < totalLength {
					mentorChar := input[j%patternLength]
					if byte(char-32) == mentorChar {
						countMentors++
					}
				}
			}
		}
	}
	fmt.Println(countMentors)
}
